# Generated by Django 2.1.5 on 2020-07-22 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('clientes', '0004_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
