# Generated by Django 2.1.5 on 2020-08-04 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0006_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField(default=0)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedades',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicamentos',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
