# Generated by Django 2.1.5 on 2020-08-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20200803_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
