# Generated by Django 2.1.5 on 2020-08-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
        ('clientes', '0008_medico_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicos.Doctor'),
        ),
    ]
