# Generated by Django 2.1.5 on 2020-08-13 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_paciente_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='user',
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
    ]
